<?php

/**
 * implement hook_field_formatter_info()
 */
function sse_fff_field_formatter_info() {
  return [
    'file_sse_sidebar' => [
      'label' => t('SSE 侧边栏项'),
      'field types' => ['file']
    ]
  ];
}

/**
 * implement hook_field_formatter_view()
 */
function sse_fff_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = [];
  switch ($display['type']) {
    case 'file_sse_sidebar':
      foreach ($items as $delta => $item) {
        $element[$delta] = [
          '#markup' => 
            '<div class="relative-link__item">'.
              '<i class="relative-link__icon icon-attach_file"></i>'.
              l((isset($item['description']) ? $item['description'] : $item['filename']), file_create_url($item['uri'])).
            '</div>'
        ];
      }
      break;
  }
  return $element;
}
